name: Scrape Data
on: push
jobs:
  scrape-data-job:
    name: Scrape Data Job
    runs-on: [ubuntu-latest]
    container: docker://dvcorg/cml-py3:latest
    steps:
      - uses: actions/checkout@v2
      - name: Run Script
        env:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          TWITTER_TOKEN: ${{ secrets.TWITTER_TOKEN }}
  
        run: |
          pip install -r requirements.txt
          python train.py

    
