name: Scrape Data
on: push
jobs:
  scrape-data-job:
    name: Scrape Data Job
    runs-on: [ubuntu-latest]
    container: docker://dvcorg/cml-py3:latest
    steps:
      - uses: actions/checkout@v2
      - name: Run Script
  
        run: |
          # Your ML workflow goes here
          pip install -r requirements.txt
          python train.py
        with:
          TWITTER_TOKEN: ${{ secrets.TWITTER_TOKEN }}

    
