name: Scrape Data
on: push
jobs:
  test-job:
    name: Test Job
    runs-on: ubuntu-latest
    steps:
      - name: Show Greeting
        uses: mscoutermarsh/ascii-art-action@master
        with:
          text: 'Hello, world.'
  scrape-data-job:
    name: Scrape Data Job
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v2
      - name: Setup Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.8
      - name: Run Script
        run: 
          python scrape.py
        env:
          TWITTER_TOKEN: ${{ secrets.TWITTER_TOKEN }}

    
