name: Fetch Yesterdays Tweets
on:
  push
  #schedule:
  #  - cron: '0 5 * * *'
    
jobs:
  scrape-data-job:
    name: Fetch Yesterdays Tweets
    runs-on: ubuntu-18.04
    steps:
      - name: Checkout Repository.
        uses: actions/checkout@v2


      - name: Setup Python 3.7.
        uses: actions/setup-python@v2
        with:
          python-version: '3.7' 


      - name: Decrypt Secrets file.
        run: ./.github/scripts/decrypt_secret.sh
        env:
          SECRET_PASSPHRASE: ${{ secrets.SECRET_PASSPHRASE }}


      - name: Install dependencies and run script.
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          python scrape.py
        env:
          CONSUMER_KEY: ${{ secrets.CONSUMER_KEY }}
          CONSUMER_SECRET: ${{ secrets.CONSUMER_SECRET }}
          ACCESS_TOKEN: ${{ secrets.ACCESS_TOKEN }}
          ACCESS_TOKEN_SECRET: ${{ secrets.ACCESS_TOKEN_SECRET }}


      - name: Commit data to repo.
        run: |
          git config --global user.email "joshkraft757@gmail.com"
          git config --global user.name "Josh Kraft"
          git add .
          git commit -m "Commit daily tweet data."
          git push
